BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Player" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL UNIQUE,
	"skin"	INTEGER NOT NULL,
	"x"	REAL NOT NULL,
	"y"	REAL NOT NULL,
	"z"	REAL NOT NULL,
	"rotation"	REAL NOT NULL,
	"interior"	INTEGER NOT NULL,
	"dimension"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "Player" VALUES (3,'Bringa',0,44.878906,-596.40918,4.926391,288.98053,0,0);
COMMIT;
